config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "events#index"
  resources :events do
    collection do
      get :results
      get :search
      get :demoform
  end

  
  end

  resources :tags

  resources :comments

  resources :users do
    collection do
      get :results
      get :search
      
    end
  end

  resources :photos do
    collection do
      get :results
      get :search

    end
  member do 
      get :download_photo_pic 
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
	# attr_accessible :message, :name
	has_and_belongs_to_many :photos
	has_and_belongs_to_many :tags
	has_many :comments, as: :liked
	accepts_nested_attributes_for :photos
	accepts_nested_attributes_for :comments
	validates_presence_of :title


  



	# def formatted_name
	# 	first_name + " " + last_name
 # 	end  
 ## ^ this is more common in helpers, not models
	
 # pretend events table has :expected_attendance and :attendance (both integer)
 def attendance_gap
   attendance - expected_attendance  
   # //this should be good if attendance and expected_attendance is an integer
 end
 # anywhere, @event.attendance_gap
 # e.g. @event = Event.find(1)
 # @event.attendance = 1000
 # @event.expected_attendance = 2000
 # @event.attendance_gap 
 # => 1000

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index 
    @events = Event.all
    @photos = Photo.all
  end


  def new
    @event = Event.new
    @event.photos.build
    
  end

  # def create
  #   @new_event = Event.new(event_params)
  #   if @new_event.save
  #     redirect_to events_path
  #   else
  #     redirect_to new_event_path
  #   end
  # end

  def create
    @event = Event.new(event_params)
    if @event.save
    respond_to do |format|
      format.js  { render json: @event }
      format.html { redirect_to events_path }
    end
  else 
    respond_to do |format|
      format.js 
      format.html { redirect_to events_path, notice: "update failed." }
    end
  end
end


  def show
    @event = Event.find(params[:id])
    @new_comment = @event.comments.build
    @new_tag = @event.tags.build
    # @photos = []
    # until @photos.count == 4 do
    # photo = Photo.find(rand(1..Photo.all.count))
    # @photos << photo unless @photos.include?(photo)
  end
# end


  def demoform
    @new_event = Event.new
  end

    
  

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      redirect_to events_path
    else
      redirect_to event_path
    end
  end

  def destroy
    @event = Event.find(params[:id])
      if @event.delete
      redirect_to events_path
    end
  end

  def download_photo_pic
    @photo = Photo.find(params[:id])
    file = @photo.photo_pic
    send_file file.path
  end

  def search
    @search_results  = Event.search(params[:search])
    render results_events_path
  end


  def results
  end 

  private

  def event_params
    params.require(:event).permit!
  end 

end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper

	def first_one
		Photo.first
	end

	def last_one
		Photo.last
	end

	def take_one
		Photo.take
	end

	def formatted_date(date)
		date.strftime("%Y")
	end
	# in my view, I can call e.g.
	# .div
	#	  = formatted_date(@event.event_date)
	#  ^ this would output the event's event date as its year "2014"
	# this keeps me from having to do:
	#   = @event.event_date.strftime("%Y")
	# every time in my view when i wanna format a date

	


	 

end

app/views/events/_form.html.haml
= f.label :title
%br
= f.text_field :title 
%p
= f.label :description
%br
= f.text_field :description
%br
= f.fields_for :photos do |ff|
	%p
	=ff.label :name
	%br
	=ff.text_field :name
	%br
	%br
	=ff.file_field :photo_pic
	%br
	-ff.hidden_field :photo_pic
	%br

app/views/events/_form_three.html.haml
= f.label :title
%br
= f.text_field :title 
%p
= f.label :description
%br
= f.text_field :description
%br
= f.label :Date
%br
= f.date_select :date_time
%br
/ = f.label :attending
/ %br
/ = f.radio_button :attending
/ %br

app/views/events/_search.html.haml
= form_tag search_events_path, method: "get" do
  %form.navbar-form.pull-left
    .input-group{:style => "max-width:470px;"}
      %input#srch-term.form-control{:name => "search[name]", :placeholder => "Search Coupons", :type => "search[name]"}
        .input-group-btn
          %button.btn.btn-default.btn-primary{:type => "submit"}

            %i.glyphicon.glyphicon-search

app/views/events/demoform.html.haml
%br
%br
.col-xs-5.col-sm-5
	.panel.panel-default
		.img.thumbnail
			%h2 New Event
			=form_for @new_event, url: events_path do |f|
				=render "form_three", f: f
				%br
				= f.submit "Add Event", :class => "button btn btn-primary"

app/views/events/edit.html.haml
= form_for @event, url: "/events/#{@event.id}" do |f|
	= render 'form', f: f
	= f.submit "EDIT"

%br
= link_to 'Back', events_path, method: "get"

app/views/events/index.html.haml
%br
- @events.each do |m|
  - m.photos.each do |photo|
    / - photo.comments.each do |comment|
    .col-sm-3.col-xs-6
      .panel.panel-default
        .panel-thumbnail
          = image_tag photo.photo_pic.url ,:style => "max-width: 100%"
          .panel-body
          - if user_signed_in?
            = m.title
            = link_to 'Edit', edit_event_path(m)
            = link_to 'Delete', event_path(m), :method => :delete, :data => { :confirm => 'Are you sure?' }
            %br
            %br
            = button_to "More Info!", event_path(photo), method: :get
            / = form_for [@liked, Comment.new] do |c|
            /   %ol.formList
            /     %li
            /       = c.label :message
            /       = c.text_area :message, :rows => 1
            /     %li= submit_tag "Tag"

          



             


            
            
                       
            
              

app/views/events/new.html.haml
%br
%br
.col-xs-5.col-sm-5
	.panel.panel-default
		.img.thumbnail
			%h2 New Event
			=form_for @event, url: events_path do |f|
				=render "form", f: f
				%br
				= f.submit "Add Event", :class => "button btn btn-primary"

app/views/events/show.html.haml
%br
%br
.col-xs-5.col-sm-5
  .panel.panel-default
    .img.thumbnail
      = image_tag @event.photos.first.photo_pic.url
      .panel-body
        %p.lead
        = @event.title
        %br
        %br
        = @event.description
        - @event.comments.each do |t|
          = t.message
          %br
          %br


        .container{:style => "float:center;"}
          = form_for @new_comment do |f|
            = f.hidden_field :liked_id, value: @new_comment.liked_id
            = f.hidden_field :liked_type, value: @new_comment.liked_type
            = f.text_field :message
            = f.submit "Comment!"
        %br


        .container{:style => "float:center;"}
          = form_for @new_tag, url: tags_path, method: :post do |f|
            = hidden_field_tag :event_id, @event.id
            = f.text_field :name
            = f.submit "Tag!"
        %br

        .social-likes.social-likes_light{"data-counters" => "no"}
          .facebook{:title => "Share link on Facebook"} Facebook
          .twitter{:title => "Share link on Twitter"} Twitter
          .plusone{:title => "Share link on Google+"} Google+ 



%br
- @event.tags.each do |t|
  .tagss
    = t.name

%br    
%br
%br
  
/ - @photos.each do |p|
/   .col-xs-4.col-sm-4
/     .panel.panel-default
/       .img.thumbnail
/         = image_tag p.photo_pic






/ - @events.each do |m|
/   - m.photos.each do |photo|
/     / - photo.comments.each do |comment|
/     .col-sm-3.col-xs-6
/       .panel.panel-default
/         .panel-thumbnail
/           = image_tag photo.photo_pic.url ,:style => "max-width: 100%"
/           .panel-body

/ / - @event.photos.each do |photo|
/ /   = image_tag photo.photo_pic.url