config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "events#index"
  resources :events do
    collection do
      get :results
      get :search
      get :demoform
  end

  
  end

  resources :tags

  resources :comments

  resources :users do
    collection do
      get :results
      get :search
      
    end
  end

  resources :photos do
    collection do
      get :results
      get :search

    end
  member do 
      get :download_photo_pic 
    end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	# attr_accessible :message, :name
	has_and_belongs_to_many :events
	has_many :comments, as: :liked
	accepts_nested_attributes_for :comments 
	mount_uploader :photo_pic, PhotoPicUploader
	# validates_presence_of :photo_pic

	def self.find_four
		find([5, 6, 7, 8])
	end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index 
    @photos = Photo.all
  end

  def new
    @new_photo = Photo.new
  end

  def create
    @new_photo = Photo.new(photo_params)
    if @new_photo.save
      redirect_to photos_path
    else
      redirect_to new_photo_path
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @new_comment = @photo.comments.build
  
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      redirect_to photos_path
    else
      redirect_to photo_path
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
      if @photo.delete
      redirect_to photos_path
    end
  end

  def search
    @search_results  = Photo.search(params[:search])
    render results_photos_path
  end


  def results
  end 

  def download_photo_pic
    @photo = Photo.find(params[:id])
    file = @photo.photo_pic
    send_file file.path
  end


  private

  def photo_params
    params.require(:photo).permit(comments_attributes: :message)
  end 

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
.container_form
  .col-lg-8.col-md-8.col-sm-8
    .span1
      .span10
      = f.label :name
      = f.text_field :name, class: "form-control"
      %br
      = f.file_field :photo_pic


 
 

app/views/photos/_form_two.html.haml
/ = @photos

/ %br
/ - @photos.each do |m|
/   .col-sm-3.col-xs-6
/     .panel.panel-default
/       .panel-thumbnail
/       = image_tag m.photo_pic.url ,:style => "max-width: 100%"
/       .panel-body


/ = image_tag @photos.photo_pic.url
      
    

app/views/photos/_search.html.haml
.top-search 
  %br
  = form_tag search_photos_path, method: "get" do
    = text_field_tag 'search[name]'
    = submit_tag "SEARCH"

app/views/photos/edit.html.haml
= form_for @photo, url: "/photos/#{@photo.id}" do |f|
	= render "form", f: f
	= f.submit "EDIT"



= link_to "DELETE",  {:action => "destroy", :id => "#{@photo.id}"}, :method => :delete, :class => "icon-delete", :confirm => "Are you sure"

app/views/photos/index.html.haml
%br
- @photos.each do |m|
  .col-sm-3.col-xs-6
    .panel.panel-default
      .panel-thumbnail
      = image_tag m.photo_pic.url ,:style => "max-width: 100%"
      .panel-body
        %p.lead
          = m.name  
          %p
          %a{:href => "/photos/#{m.id}/edit"} Edit
          %a{:href => "/photos/#{m.id}/edit"} Delete
          %br
          

app/views/photos/new.html.haml
=form_for @new_photo, url: photos_path do |f|
  = render "form", f: f
  = f.submit "Create New"

app/views/photos/results.html.haml
- @search_results.each do |d|
  .col-sm-4.col-xs-6
    .panel.panel-default
      .panel-thumbnail

        = image_tag d.photo_pic.url ,:style => "max-width: 100%"

      .panel-body
        %p.lead 
        = d.title
        %p 
          = d.description
          %br
        %p
          %a{:href=>"/photos/#{d.id}/edit"} EDIT
          %a{:href=>"/photos/#{d.id}/edit"} DELETE
          %br
          = link_to "Download Photo", download_photo_pic_photo_path(d)

app/views/photos/show.html.haml
- @photo.each do |m|
  .col-sm-3.col-xs-6
    .panel.panel-default
      .panel-thumbnail
        = image_tag m.photo_pic.url ,:style => "max-width: 100%"
        






/ %br
/ - @photos.each do |m|
/   - m.events.each do |photo|
/     / - photo.comments.each do |comment|
/     .col-sm-3.col-xs-6
/       .panel.panel-default
/         .panel-thumbnail
/           = image_tag m.photo_pic.url ,:style => "max-width: 100%"
/           .panel-body
/             %p.lead
/             %ul#comments
/             %li
/             = @liked
/             %br
/             = form_for @new_comment, url: photo_path, method: :post do |f|
/               = f.hidden_field :liked_id, value: @new_comment.liked_id
/               = f.hidden_field :liked_type, value: @new_comment.liked_type
/               = f.text_field :message
/               = f.submit "Tag"

app/views/photos/toolbox.html.haml
= link_to 'Delete', photo_path(m), photo, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br
- @photos.each do |m|
  .col-sm-3.col-xs-6
    .panel.panel-default
      .panel-thumbnail
      = image_tag m.photo_pic.url ,:style => "max-width: 100%"
      .panel-body
        %p.lead
          = m.name  
          %p
          %a{:href => "/photos/#{m.id}/edit"} Edit
          %a{:href => "/photos/#{m.id}/edit"} Delete
          %br
          = form_for @photo, url: 'photos/#{@photo.id', method: "put" |f|
            = f.fields_for :comments do |ff|
            = ff.text_field :message
            = f.submit

          
            = link_to "Download Photo", download_photo_pic_photo_path(m)
            .social-likes.social-likes_light{"data-counters" => "no"}
              .icon-facebook{:title => "Share link on Facebook"} Facebook
              .icon-twitter-t{:title => "Share link on Twitter"} Twitter
              .icon-google-plus{:title => "Share link on Google+"} Google+ 

app/views/photos/untitled.haml
= link_to 'Delete', photo_path(m), photo, :method => :delete, :data => { :confirm => 'Are you sure?' }

/ .divtwo
/   .col-sm-3.col-xs-6
/     .panel.panel-default
/       .panel.thumbnail
/         = image_tag @photos.third.photo_pic.url

/ .divthree
  / .col-sm-3.col-xs-6
  /   .panel.panel-default
  /     .panel.thumbnail
/         = image_tag @photos.third.photo_pic.url


/ .divfour
/   .col-sm-3.col-xs-6
/     .panel.panel-default
/       .panel.thumbnail
/         = image_tag @photos.third.photo_pic.url


/ .divfive
/   .col-sm-3.col-xs-6
/     .panel.panel-default
/       .panel.thumbnail
/         = image_tag @photos.third.photo_pic.url


/ .divsix
/   .col-sm-3.col-xs-6
/     .panel.panel-default
/       .panel.thumbnail
/         = image_tag @photos.third.photo_pic.url


/ .divseven
/   .col-sm-3.col-xs-6
/     .panel.panel-default
/       .panel.thumbnail
/         = image_tag @photos.third.photo_pic.url


/ .diveight
/   .col-sm-3.col-xs-6
/     .panel.panel-default
/       .panel.thumbnail
/         = image_tag @photos.third.photo_pic.url

/ .divnine
/   .col-sm-3.col-xs-6
/     .panel.panel-default
/       .panel.thumbnail
/         = image_tag @photos.third.photo_pic.url

/ .divten
/   .col-sm-3.col-xs-6
/     .panel.panel-default
/       .panel.thumbnail
/         = image_tag @photos.third.photo_pic.url
              


.col-sm-8.col-xs-8
  #pics
    %img
      #divone{:height => "100", :width => "100"}
        = image_tag @photos.first.photo_pic.url
      #divtwo{:height => "100", :width => "100"}
        = image_tag @photos.second.photo_pic.url
      #divthree{:height => "100", :width => "100"}
          = image_tag @photos.third.photo_pic.url
      #divfour{:height => "100", :width => "100"}
          = image_tag @photos.fourth.photo_pic.url
      #divfive{:height => "100", :width => "100"}
        = image_tag @photos.fifth.photo_pic.url
    / %img#divsix{:height => "100", :width => "100"}
    /   = image_tag @photos.sixth.photo_pic.url
    / %img#divseven{:height => "100", :width => "100"}
    /   = image_tag @photos.seventh.photo_pic.url
    / %img#diveight{:height => "100", :width => "100"}
    /   = image_tag @photos.eighth.photo_pic.url
    / %img#divnine{:height => "100", :width => "100"}
    /   = image_tag @photos.ninth.photo_pic.url




%br
- @photos.each do |m|
  .col-sm-3.col-xs-6
    .panel.panel-default
      .panel-thumbnail
      = image_tag m.photo_pic.url ,:style => "max-width: 100%"
      .panel-body
        %p.lead
          = m.name  
          %p
          %a{:href => "/photos/#{m.id}/edit"} Edit
          %a{:href => "/photos/#{m.id}/edit"} Delete
          %br
              